spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/v1/members/**

            - id: workout-service
              uri: lb://WORKOUT-SERVICE
              predicates:
                - Path=/api/v1/workouts/**

            - id: fitness-service
              uri: lb://FITNESS-SERVICE
              predicates:
                - Path=/api/v1/fitnesses/**

            - id: member-users
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: member-trainers
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/v1/trainers/**

          default-filters:
            - PreserveHostHeader
            - AuthenticationFilter

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"

server:
  port: 8000